smtp:
  address: 'smtp.gmail.com'
  port: 587
  domain: 'gmail.com'
  user_name: 'mecolamarino@gmail.com'
  password: '155610565'
  authentication: 'plain'
  enable_starttls_auto: true
  
public_host: 'localhost'
