development:
  adapter: postgresql
  encoding: unicode
  database: mate_development
  pool: 5
  username: mate
  password: mate

test:
  adapter: postgresql
  encoding: unicode
  database: mate_test
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'mate' %>
  password: <%= ENV['TRAVIS'] ? '' : 'mate' %>

production:
  adapter: postgresql
  encoding: unicode
  database: mate_production
  pool: 5
  username: mate
  password: mate
